version: '3.8'
services:
  rag-api:
    user: "0:0"  # Run as root temporarily
    environment:
      - HF_HOME=/app/models/huggingface
      - TRANSFORMERS_CACHE=/app/models/transformers  
      - USE_MOCK_EMBEDDINGS=true  # Skip model download
    volumes:
      - rag_cache:/app/models  # Add cache volume

volumes:
  rag_cache:
    driver: local
